## Rename this file to .gitlab-ci.yml
stages:
  - build
  - lint
  - test  # ✅ Added test stage

# BUILD STAGE
build-backend:
  stage: build
  image: gradle:7.5-jdk17
  script:
    - cd backend
    - gradle clean build -x test -x check
  rules:
    - when: always
  allow_failure: false

# LINT STAGE
lint-backend:
  stage: lint
  image: gradle:7.5-jdk17
  script:
    - cd backend
    - gradle check
  rules:
    - when: always
  allow_failure: false

lint-frontend:
  stage: lint
  image: node:16
  script:
    - cd frontend
    - npm install
    - npx eslint . --ext .js,.jsx
  rules:
    - when: always
  allow_failure: false

# ✅ TEST STAGE (NEW) - Runs Pytest and Coverage
test-python:
  stage: test
  image: python:3.12  # ✅ Use latest Python image
  before_script:
    - cd ingestor  # ✅ Change directory to ingestor before running commands
    - pip install --upgrade pip
    - pip install pytest coverage  # ✅ Install pytest & coverage
    - pip install -r requirements.txt  # ✅ Install dependencies
  script:
    - coverage run -m pytest tests/test.py  # ✅ Run tests with coverage
    - coverage report -m  # ✅ Show coverage report in console
  artifacts:
    paths:
      - coverage_html_report/  # ✅ Store coverage results for review
  rules:
    - when: always
  allow_failure: false
  