version: '3.8' # Specifies the Docker Compose file version

services:
  # Reverse proxy service
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000 # User ID for permissions
      - PGID=1000 # Group ID for permissions
      - TZ=Etc/UTC # Time zone setting
      - URL=sociend.socs.uoguelph.ca # Domain name
      - VALIDATION=http # Method for SSL validation
      - STAGING=false # Whether to use staging environment
    volumes:
      - ./swag/config:/config # Mount configuration volume
    ports:
      - 443:443 # HTTPS port
      - 80:80 # HTTP port
    depends_on:
      - frontend # Ensures frontend starts before swag
    networks:
      - swag-frontend # Network for communication with frontend
    restart: unless-stopped # Restart policy

  # Backend service
  backend:
    build: ./backend # Builds from the backend directory
    ports:
      - "8080:8080" # Maps container port 8080 to host port 8080
    environment:
      - DB_ADDRESS=jdbc:mysql://database:3306 # JDBC URL for database
      - DB_DATABASE=template_db # Database name
      - DB_USER=root # Database username
      - DB_PASSWORD=pwd # Database password
    networks:
      - backend-database # Network to connect with database
      - backend-frontend # Network to connect with frontend

  # Database service
  database:
    build: ./database # Builds from the database directory
    environment:
      - MYSQL_ROOT_PASSWORD=pwd # Root password for MySQL
      - MYSQL_DATABASE=template_db # Initial database name
    volumes:
      - mariadb_data:/var/lib/mysql # Persistent database storage
    networks:
      - backend-database # Network for backend communication
      - ingester-database # Network for ingestor communication
    ports:
      - "3306:3306" # Exposes MySQL port
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-ppwd" ] # Checks if MySQL is running
      interval: 10s # Check every 10 seconds
      retries: 15 # Retry up to 15 times
      start_period: 40s # Wait 40 seconds before first check
      timeout: 5s # Timeout for health check

  # Frontend service
  frontend:
    build: ./frontend # Builds from the frontend directory
    ports:
      - "3000:3000" # Maps frontend container port to host
    environment:
      - BACKEND_PROXY=http://backend:8080 # Proxy URL for backend
    networks:
      - backend-frontend # Connects to backend
      - swag-frontend # Connects to reverse proxy

  # Data ingestion service
  ingestor:
    build: ./ingestor # Builds from the ingestor directory
    environment:
      - DB_HOST=database # Database host
      - DB_DATABASE=template_db # Database name
      - DB_USER=root # Database username
      - DB_PASSWORD=pwd # Database password
    depends_on:
      - database # Ensures database starts before ingestor
    networks:
      - ingester-database # Connects to database

volumes:
  mariadb_data:
    # Defines a named volume for MySQL data persistence

networks:
  backend-database: # Network connecting backend and database
  backend-frontend: # Network connecting backend and frontend
  ingester-database: # Network connecting ingestor and database
  swag-frontend: # Network connecting reverse proxy and frontend
